version: "3.7"
services:
  php-cli:
    build:
      context: ./php-8.1
      target: php-cli
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_NAME=event_sourcing_dbal
      - DATABASE_URL=mysql://root:root@mysql:3306/event_sourcing_dbal
    links:
      - mysql
    volumes:
      - ../:/var/www:delegated
    working_dir: /var/www/

  mysql:
    build:
      context: ./php-8.1
      target: mysql
    environment:
      - MYSQL_DATABASE=event_sourcing_dbal
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
